language: cpp
dist: bionic
os: linux
cache: ccache
branches:
  only:
  - master
  - devel
compiler:
- gcc
before_install:
- git submodule update --init --recursive
addons:
  apt:
    update: true
    packages:
      - doxygen
      - doxygen-latex
      - libboost-all-dev
      - libtinyxml-dev
script: ./.travis/build
